metrics-server:
  #hostNetwork: true
  #securePort: 4443
  apiService:
    create: true
  extraArgs:
    kubelet-insecure-tls: true
    kubelet-preferred-address-types: InternalIP
    #cert-dir: /tmp
    #secure-port: 4443
  resources:
    limits:
      cpu: 250m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 64Mi