---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluentbit
  namespace: argocd
spec:
  destination:
    namespace: logging
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
    path: fluentbit
    repoURL: 'https://github.com/debu99/test-repo.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  destination:
    namespace: ingress
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
    path: traefik
    repoURL: 'https://github.com/debu99/test-repo.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
