---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluentbit
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  destination:
    namespace: logging
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    helm:
      valueFiles:
      - dev/values.yaml
    path: fluentbit
    repoURL: 'https://github.com/debu99/test-repo.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluentbit-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "8"
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: logging
  project: default
  source:
    repoURL: 'https://github.com/debu99/test-repo.git'
    path: fluentbit-secrets/dev/
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "99"
spec:
  destination:
    namespace: ingress
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    helm:
      valueFiles:
      - dev/values.yaml
    path: traefik
    repoURL: 'https://github.com/debu99/test-repo.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  destination:
    namespace: secret
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    helm:
      valueFiles:
      - dev/values.yaml
    path: kubernetes-external-secrets
    repoURL: 'https://github.com/debu99/test-repo.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
