velero:
  initContainers: 
    - name: velero-plugin-for-aws
      image: velero/velero-plugin-for-aws:v1.1.0
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /target
          name: plugins
  enableHelmHooks: false
  configuration:
    provider: aws
    backupStorageLocation:
      name: notejam-eks-backup
      bucket: notejam-eks-backup
      config: 
        region: ap-southeast-1
    volumeSnapshotLocation:
      name: volumeSnapshot
      config: 
        region: ap-southeast-1
      logLevel: debug
  credentials:
    useSecret: false
  serviceAccount:
    server:
      create: true
      name: velero-server
      annotations:
        eks.amazonaws.com/role-arn: "arn:aws:iam::702051619253:role/notejam-velero"
  securityContext:
    fsGroup: 65534
  snapshotsEnabled: false
  schedules:
    mybackup:
      labels:
        env: dev
      schedule: "0 0 * * *"
      template:
        ttl: "48h"
        includedNamespaces:
        - dev