---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: fluentbit
spec:
  backendType: systemManager
  data:
    - key: /fluentbit/dev/FLUENT_ELASTICSEARCH_USER
      name: password
    - key: /fluentbit/dev/FLUENT_ELASTICSEARCH_PASSWORD
      name: password