---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: velero
spec:
  backendType: systemManager
  data:
    - key: /velero/dev/AWS_ACCESS_KEY_ID
      name: AWS_ACCESS_KEY_ID
    - key: /velero/dev/AWS_SECRET_ACCESS_KEY
      name: AWS_SECRET_ACCESS_KEY