fluent-bit:
  serviceMonitor:
    enabled: true
    namespace: monitoring
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  env:
    - name: FLUENT_ELASTICSEARCH_HOST
      value: "40cc384c9f0d4e31bd126ac33024e525.ap-southeast-1.aws.found.io"
    - name: FLUENT_ELASTICSEARCH_PORT
      value: "9243"
  envFrom:
    - secretRef:
        name: fluentbit
  config:
    outputs: |
      [OUTPUT]
          Name es
          Match kube.*
          Host ${FLUENT_ELASTICSEARCH_HOST}
          Port ${FLUENT_ELASTICSEARCH_PORT}
          HTTP_User ${FLUENT_ELASTICSEARCH_USER}
          HTTP_Passwd ${FLUENT_ELASTICSEARCH_PASSWORD}
          Logstash_Format On
          Replace_Dots    On
          Retry_Limit False
          tls On
          tls.verify Off

      [OUTPUT]
          Name es
          Match host.*
          Host ${FLUENT_ELASTICSEARCH_HOST}
          Port ${FLUENT_ELASTICSEARCH_PORT}
          HTTP_User ${FLUENT_ELASTICSEARCH_USER}
          HTTP_Passwd ${FLUENT_ELASTICSEARCH_PASSWORD}
          Logstash_Format On
          Logstash_Prefix node
          Retry_Limit False
          tls On
          tls.verify Off

